### PR TITLE
Normalize paths in the ZIP file

### LINKED ISSUE #28: Remove invalid characters in filename
Check: http://en.wikipedia.org/wiki/Filename#Reserved%5Fcharacters%5Fand%5Fwords

We should not write down filenames containing those characters, since they are forbidden on OS level, or produces side effects.

### PR DESCRIPTION
**Pull request by jone**
The representations normally do not normalize the filenames and paths added to the ZIP.
The source of the names by a title field, for example.
This can lead to problems when characters are used which are invalid on the file system.

This pull-request adds path normalization for all added files directly in the generator.

**Allowed characters:**
- Alphanumeric characters (``A-Z``, ``a-z``, ``0-9``)
- Normal brackets (`(` and `)`)
- Dots, dashes, underscores (`.`, `_`, `-`)
- OS path seperator (usually `/`, on windows `\`; separates directories / files)
- ~~Umlauts (generated with unicode data tools so that we do not miss exotic umlauts)~~

**Invalid characters:**
Invalid characters are replaced with a dash `-`.

**Slashes:**
Slashes (`/`) and backslashes (`\`) are always converted to forward slashes (`/`),
since the zipfile standard module always uses forward slashes.
http://stackoverflow.com/a/5040351/880628

**Umlauts:**
~~The list of umlauts is generated once and cached.
It is generated by combining all combination characters (diacritics) with all characters in the alphabet and try to combine them.~~

**External usage:**
Representations may rely on knowing the actually used path.
If this is the case, they must use the `normalize_path` function before adding the path, so that they know the normalize path:
```python
from ftw.zipexport.utils import normalize_path

    def get_files(self, path_prefix=u"", recursive=True, toplevel=True):
        ....
        path = normalize_path(path)
        yield (path, data)
```

**Customization (copied from readme)**:

Paths are automatically using Plone's ``IFileNameNormalizer``.
If you want to use a custom normalization, you  can pass it to the ``ZipGenerator``:

```python
    from ftw.zipexport.generation import ZipGenerator
    from Products.CMFPlone.utils import safe_unicode
    import re

    def normalize_path(path):
        path = safe_unicode(path).replace(u'\\', u'/')
        return re.sub(ur'[^\w\-.\/]', u'', path)

    with ZipGenerator(path_normalizer=normalize_path) as zipgenerator:
        ...
```

Pass ``None`` to disable normalization completely:

```python
    from ftw.zipexport.generation import ZipGenerator

    with ZipGenerator(path_normalizer=None) as zipgenerator:
        ...
```

Closes #28 
@shylux 
/cc @maethu @lukasgraf

### CODE REVIEW

**Comment by maethu** [comment]
Nice! :+1:

**Comment by lukasgraf** [comment]
@jone I don't think I agree on allowing umlauts and other diacritic characters.

What makes diacritics so special (in the sense of "less problematic") that you would allow them, but not ligatures (`ß`, `&`, `æ`, ...)? Why not greek letters (`α`, `β`, `γ`, ...)? And what's wrong with other non-alpha numeric characters from ASCII (`$`, `=`, `%`, ...)?

My point is that this rule currently seems completely arbitrary. Why diacritics? Because German umlauts are common in the filenames we encounter on a daily basis? Then why not just whitelist *those* umlauts, instead of allowing a ton of diacritics that have no relevance in our language region, and span a multitude of different character sets?

**Comment by jone** [comment]
@lukasgraf I've refactored to use Plone's ``IFileNameNormalizer`` instead.
It also possible to use a custom normalization function by passing it to the generator on initialization.

**Comment by lukasgraf** [comment]
@jone :+1:!

**Pull request merged**
